#!/bin/sh
#
# Kernel post-install hook for dracut EFI bundle.
#
# Arguments passed to this script: $1 pkgname, $2 version.
#
PKGNAME="$1"
VERSION="$2"

. "${ROOTDIR}/etc/default/dracut-uefi-hook"
if [ -z "${CREATE_UEFI_BUNDLES}" ]; then
	exit 0
fi

if [ ! -x usr/bin/dracut ]; then
	exit 0
fi

mkdir -p ${UEFI_BUNDLE_DIR:=boot/efi/EFI}

usr/bin/dracut -q --force ${DRACUT_OPTIONS} \
	${KERNEL_CMDLINE:+--kernel-cmdline="${KERNEL_CMDLINE}"} \
	--uefi ${UEFI_BUNDLE_DIR}/linux-${VERSION}.efi ${VERSION}

sbctl sign -s /boot/efi/EFI/linux-${VERSION}.efi

cp /boot/efi/EFI/linux-${VERSION}.efi /boot/efi/EFI/backup/

mv /boot/efi/EFI/linux-${VERSION}.efi /boot/efi/EFI/linux.efi

